name: ui_common
description: ui commons
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.3

  flutter_screenutil: ^5.8.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true